### ISSUE TITLE
Worksheet is not saving if ID column is not present and enumerated

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#37]
This issue is happening on 2 of Elm students machine. They will provide screenshots, once they get tcpd github access.

**Comment by Sudesh-Prakash-Singh** [comment]
Figured out the cause of the issue.
It happens when there is no 'ID' field in the worksheet. Which is usually the case when the worksheet is being loaded for the first time.

Creating an 'ID' field with number series in excel or R is a temporary workaround for now.

**Comment by Sudesh-Prakash-Singh** [comment]
Changed Issue title to a more relevant one.

**Comment by hangal** [comment]
@sudesh-ashoka should be fixed now, pls test.

**Comment by Sudesh-Prakash-Singh** [comment]
I tested this on surf-standalone-32.jar, and the issue still seems to be there.

**Comment by hangal** [comment]
@sudesh-ashoka can you pls try it on the latest build? thnx
